"""Build a small synthetic step-06 fixture from a real year's SOY_MUN data.

Useful when step-06 outputs are missing (e.g. for years where ANTAQ cargo data
isn't available) and we just want to validate the LP pipeline end-to-end on
realistic-but-tractable data.

What it builds (under `data/generated/outputs/06_{YEAR}_smoke/parquet/`):
  - stations_orig.parquet, stations_dest.parquet   ← 2 synthetic rail hubs
  - ports_orig.parquet,    ports_dest.parquet      ← 2 synthetic inland-waterway hubs
                                                     (river barge nodes, not seaports
                                                      — keeps Stefan's GAMS file names)
  - cargo_rail_long.parquet, cargo_water_long.parquet  ← generous capacities
  - {road_dist_MUN, road_dist_MUN_stat, …, rail_dist, water_dist}_long.parquet
    All distances derived from MUN_capital_dist.rds (great-circle, in metres).

It does NOT touch the real data/generated/outputs/06_{YEAR}/ directory.

Usage:
  python code/pipeline/transport_lp/make_fixture.py 2013                 # 20 origin MUs
  python code/pipeline/transport_lp/make_fixture.py 2013 --n-mun 50      # 50 origin MUs
  python code/pipeline/transport_lp/make_fixture.py 2013 --output-suffix smoke50
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from transport_lp.data_loader import load_soy_mun, _read_parquet, _read_rds


def main():
    p = argparse.ArgumentParser()
    p.add_argument("year", type=int)
    p.add_argument("--n-mun", type=int, default=20,
                   help="number of producing municípios in the fixture (default 20)")
    p.add_argument("--output-suffix", default="smoke",
                   help="creates data/generated/outputs/06_{year}_{suffix}/")
    p.add_argument("--seed", type=int, default=42)
    args = p.parse_args()

    rng = np.random.default_rng(args.seed)

    # 1. Real SOY_MUN — pick top supply MUs AND top demand MUs so the LP is
    #    mass-balanceable. Then rescale supply within the fixture to match
    #    (total demand + intermodal capacity) so LP feasibility is guaranteed.
    print(f"[fixture] Loading SOY_MUN for {args.year}…")
    soy_full = load_soy_mun(args.year)
    soy_full["co_mun"] = soy_full["co_mun"].astype(str)
    half = max(1, args.n_mun // 2)
    sup_mus = (soy_full[soy_full["excess_supply_bean"] > 0]
                 .sort_values("excess_supply_bean", ascending=False)
                 .head(half)["co_mun"].tolist())
    dem_mus = (soy_full[soy_full["excess_use_bean"] > 0]
                 .sort_values("excess_use_bean", ascending=False)
                 .head(args.n_mun - half)["co_mun"].tolist())
    keep_mus = list(dict.fromkeys(sup_mus + dem_mus))  # dedup, preserve order
    soy = soy_full[soy_full["co_mun"].isin(keep_mus)].copy()
    print(f"[fixture] Selected {len(sup_mus)} supply + {len(dem_mus)} demand MUs "
          f"({len(soy)} unique).")
    a_ids = soy["co_mun"].tolist()

    # 2. MUN_capital_dist for road distances (from step 00). Prefer parquet long
    #    format (generated by export_to_parquet.R) so we don't need pyreadr.
    pq_long = Path(f"data/generated/outputs/00_{args.year}/parquet/MUN_capital_dist_long.parquet")
    rds_mat = Path(f"data/generated/outputs/00_{args.year}/MUN_capital_dist.rds")
    if pq_long.exists():
        print(f"[fixture] Loading {pq_long}…")
        long = pd.read_parquet(pq_long)
        long["from"] = long["from"].astype(str)
        long["to"]   = long["to"].astype(str)
        dist_full = long.pivot_table(index="from", columns="to", values="distance",
                                      fill_value=np.inf).astype(float)
    elif rds_mat.exists():
        print(f"[fixture] Loading {rds_mat} via pyreadr…")
        dist_full = _read_rds(rds_mat)
        if not isinstance(dist_full, pd.DataFrame):
            sys.exit("MUN_capital_dist.rds didn't load as a DataFrame — convert via "
                     "`Rscript code/pipeline/transport_lp/export_to_parquet.R "
                     f"{args.year}` first.")
        dist_full.index = dist_full.index.astype(str)
        dist_full.columns = dist_full.columns.astype(str)
    else:
        sys.exit(f"Need either {pq_long} or {rds_mat} — run step 00 first, then "
                 f"optionally `Rscript code/pipeline/transport_lp/export_to_parquet.R "
                 f"{args.year}` to produce parquet.")

    # Subset to our sample. Some IDs may be missing in dist_full (filtered MUs)
    keep = [m for m in a_ids if m in dist_full.index and m in dist_full.columns]
    a_ids = keep
    soy = soy[soy["co_mun"].isin(a_ids)].copy()
    print(f"[fixture] {len(a_ids)} MUs survive distance-matrix filter.")
    dist_aa = dist_full.loc[a_ids, a_ids]

    # 3. Build 2 rail hubs and 2 inland-waterway (barge) hubs as virtual nodes
    #    anchored at the geographic centroid of two random sub-clusters of our
    #    MUs. Distances from each MU to the hub are the mean of MU→{cluster mus}
    #    distances. Note: "port" here = river hub along Brazilian hidrovias, NOT
    #    seaport — we keep Stefan's GAMS naming (w1/w2, cdi_tuaria) for
    #    compatibility with code/pipeline/07_transport_GAMS_parallel.R.
    n_rail, n_port = 2, 2
    cluster_size = max(2, len(a_ids) // 4)
    rail_clusters = [rng.choice(a_ids, size=cluster_size, replace=False).tolist()
                     for _ in range(n_rail)]
    port_clusters = [rng.choice(a_ids, size=cluster_size, replace=False).tolist()
                     for _ in range(n_port)]
    r_ids_orig = [f"RAIL_O_{i}" for i in range(n_rail)]
    r_ids_dest = [f"RAIL_D_{i}" for i in range(n_rail)]
    w_ids_orig = [f"PORT_O_{i}" for i in range(n_port)]
    w_ids_dest = [f"PORT_D_{i}" for i in range(n_port)]

    stations_orig = pd.DataFrame({"CodigoTres": r_ids_orig, "name": [f"Rail Orig {i}" for i in range(n_rail)]})
    stations_dest = pd.DataFrame({"CodigoTres": r_ids_dest, "name": [f"Rail Dest {i}" for i in range(n_rail)]})
    ports_orig    = pd.DataFrame({"cdi_tuaria": w_ids_orig, "name": [f"Port Orig {i}" for i in range(n_port)]})
    ports_dest    = pd.DataFrame({"cdi_tuaria": w_ids_dest, "name": [f"Port Dest {i}" for i in range(n_port)]})

    def cluster_dist(mu_list, cluster):
        """Mean distance from each MU to MUs in a cluster."""
        rows = []
        for mu in mu_list:
            if mu in dist_full.index:
                d = dist_full.loc[mu, [c for c in cluster if c in dist_full.columns]].mean()
            else:
                d = np.nan
            rows.append(d)
        return np.array(rows)

    def make_long(from_ids, to_ids, dist_arr_2d, from_col="from", to_col="to"):
        return pd.DataFrame({
            from_col: np.repeat(from_ids, len(to_ids)),
            to_col:   np.tile(to_ids, len(from_ids)),
            "distance": dist_arr_2d.flatten(),
        }).query("distance == distance and distance >= 0").reset_index(drop=True)

    # MU → MU (road)
    road_MUN_long = make_long(a_ids, a_ids, dist_aa.to_numpy())
    # MU → rail origin
    d_MU_to_rail = np.column_stack([cluster_dist(a_ids, c) for c in rail_clusters])
    road_MUN_stat_long = make_long(a_ids, r_ids_orig, d_MU_to_rail)
    # rail destination → MU (use the same cluster anchors, distance MU→cluster)
    d_rail_to_MU = np.row_stack([cluster_dist(a_ids, c) for c in rail_clusters])
    road_stat_MUN_long = make_long(r_ids_dest, a_ids, d_rail_to_MU)
    # MU → port origin
    d_MU_to_port = np.column_stack([cluster_dist(a_ids, c) for c in port_clusters])
    road_MUN_port_long = make_long(a_ids, w_ids_orig, d_MU_to_port)
    # port destination → MU
    d_port_to_MU = np.row_stack([cluster_dist(a_ids, c) for c in port_clusters])
    road_port_MUN_long = make_long(w_ids_dest, a_ids, d_port_to_MU)

    # rail r1 → r2: assume direct connection within each cluster pair at 500 km
    rail_long = pd.DataFrame([
        {"from": ro, "to": rd, "distance": 500_000.0}
        for ro in r_ids_orig for rd in r_ids_dest
    ])
    # water w1 → w2: assume 1000 km
    water_long = pd.DataFrame([
        {"from": wo, "to": wd, "distance": 1_000_000.0}
        for wo in w_ids_orig for wd in w_ids_dest
    ])

    # Cargo capacities: generous (no binding) for each rail/water route × product
    cargo_rail = pd.DataFrame([
        {"orig": ro, "dest": rd, "product": p, "volume": 1e9}
        for ro in r_ids_orig for rd in r_ids_dest for p in ("bean", "oil", "cake")
    ])
    cargo_water = pd.DataFrame([
        {"orig": wo, "dest": wd, "product": p, "volume": 1e9}
        for wo in w_ids_orig for wd in w_ids_dest for p in ("bean", "oil", "cake")
    ])

    # ── Write the fixture ─────────────────────────────────────────────────────
    out_root = Path(f"data/generated/outputs/06_{args.year}_{args.output_suffix}")
    pq_dir = out_root / "parquet"
    pq_dir.mkdir(parents=True, exist_ok=True)

    # Rescale within the fixture so the LP is mass-balanceable.
    # Constraints for feasibility of a balanced LP:
    #   total_demand                  <= total_supply  (else can't meet demand)
    #   total_supply - total_demand   <= total_exp_proc  (excess must go intermodal)
    # i.e., total_demand <= total_supply <= total_demand + total_exp_proc.
    # If supply or demand falls outside that band, scale proportionally to fit.
    for prod in ("bean", "oil", "cake"):
        sup_col, dem_col = f"excess_supply_{prod}", f"excess_use_{prod}"
        exp_col = f"exp_{prod}"
        sup = soy[sup_col].sum()
        dem = soy[dem_col].sum()
        if prod == "bean":
            ep = (soy[exp_col] + soy["proc_bean"]).sum()
        else:
            ep = soy[exp_col].sum()
        # Choose a target supply such that dem <= sup <= dem + ep
        target_sup = max(dem, min(sup, dem + ep))
        if sup > 0 and target_sup != sup:
            scale = target_sup / sup
            print(f"[fixture] rescale {prod} supply: {sup:.0f} → {target_sup:.0f} "
                  f"(scale={scale:.4f})")
            soy[sup_col] = soy[sup_col] * scale
            sup = target_sup
        # If demand still exceeds supply, scale demand down
        if dem > sup and dem > 0:
            scale = sup / dem
            print(f"[fixture] rescale {prod} demand: {dem:.0f} → {sup:.0f} "
                  f"(scale={scale:.4f})")
            soy[dem_col] = soy[dem_col] * scale

    # SOY_MUN (downsampled) goes alongside the fixture so the loader picks it up.
    soy_root = Path(f"data/generated/outputs/05_{args.year}_{args.output_suffix}")
    soy_pq = soy_root / "parquet"
    soy_pq.mkdir(parents=True, exist_ok=True)
    soy.to_parquet(soy_pq / "SOY_MUN_fin.parquet", index=False)
    print(f"[fixture] Wrote {soy_pq/'SOY_MUN_fin.parquet'} ({len(soy)} rows)")

    def w(df, name):
        path = pq_dir / f"{name}.parquet"
        df.to_parquet(path, index=False)
        print(f"[fixture] Wrote {path} ({len(df)} rows)")

    w(stations_orig, "stations_orig")
    w(stations_dest, "stations_dest")
    w(ports_orig,    "ports_orig")
    w(ports_dest,    "ports_dest")
    w(cargo_rail,    "cargo_rail_long")
    w(cargo_water,   "cargo_water_long")
    w(road_MUN_long,      "road_dist_MUN_long")
    w(road_MUN_stat_long, "road_dist_MUN_stat_long")
    w(road_stat_MUN_long, "road_dist_stat_MUN_long")
    w(road_MUN_port_long, "road_dist_MUN_port_long")
    w(road_port_MUN_long, "road_dist_port_MUN_long")
    w(rail_long,          "rail_dist_long")
    w(water_long,         "water_dist_long")

    print(f"\n[fixture] Fixture ready under {out_root}")
    print(f"[fixture] To smoke-test the LP on this fixture:")
    print(f"          python code/pipeline/transport_lp/smoke_test.py {args.year} --suffix {args.output_suffix}")


if __name__ == "__main__":
    sys.exit(main())
